name: MiniGameEngine
version: "1.0.0"
author: "MrKitty_Cat"
api-version: 1.20
main: dev.twelveoclock.minigameengine.MiniGameEnginePlugin

commands:
  minigame:
    usage: "/minigame"
    description: "MiniGame things"